
# Copy as is, removing the dependencies you do not need.
source 'https://github.com/CocoaPods/Specs.git'
pod 'IMFGoogleAuthentication'
pod 'IMFFacebookAuthentication'
pod 'IMFPush'
pod 'IMFData'
pod 'IMFURLProtocol'
pod 'IMFCore'
